# -*- coding: utf-8 -*-
"""face Detect

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13peXXcfwDBB8VpuSRpNMHpDHiI_STIyS
"""

import cv2

image=cv2.imread('myfirst.png')

from google.colab.patches import cv2_imshow
cv2_imshow(image)
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

# haarcascade classifier->face recognition
facecasecade=cv2.CascadeClassifier('face.xml')
faces=facecasecade.detectMultiScale(gray,scaleFactor=1.2)
# ,minNeighbours=5,minSize=(20,20))
print(faces)

import cv2

webcam=cv2.VideoCapture(0)
ret ,frame=webcam.read()
print(ret)
webcam.release()